# Generated by Django 2.1.3 on 2018-11-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewhub', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('completion_date', models.DateTimeField(verbose_name='Date of Completion')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'client'), ('FRELANCERS', 'freelancers')], max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(limit_choices_to={'user_type': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviewhub.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='freelance',
            field=models.ForeignKey(limit_choices_to={'user_type': 'FRELANCERS'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviewhub.User'),
        ),
    ]
